version: '3.8'

services:
    apache:
        build:
            context: .
            dockerfile: dockerfiles/apache.dockerfile
        ports:
            - "80"

    database:
        build:
            context: .
            dockerfile: dockerfiles/postgres.dockerfile
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        env_file:
            - .envpostgres/.env

    jenkinks: 
        image: jenkins/jenkins
        ports: 
            - "8080:8080"
            - "50000:50000"
        volumes: 
            - jenkins_home:/var/jenkins_home
        depends_on:
            - database
     
volumes:
    pgdata:
    jenkins_home:

